version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ssdamy-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19077nyrzw555"
s3_prefix = "ssdamy-backend"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
